# Generated by Django 5.0.6 on 2024-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('information', models.CharField(max_length=30)),
                ('url1', models.URLField()),
                ('url2', models.URLField()),
                ('url3', models.URLField()),
            ],
        ),
    ]
