# Generated by Django 5.0.6 on 2024-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='url2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='url3',
            field=models.CharField(max_length=30),
        ),
    ]
